### ISSUE TITLE
感觉写一个page有点麻烦啊

### ISSUE THREAD

**Issue by slowpack** [hooray/one-step-admin#1]
需要在menu里面写一个module
还需要去index引入
还需要registercomponent
还要去main里面引入
😵‍💫

**Comment by slowpack** [comment]
我觉得至少要吧registercomponent,main里面引入变成默认的,然后menu里面index,import也是默认import,module,这样就只需要在view下创建文件和维护modules了

**Comment by hooray** [comment]
> 我觉得至少要吧registercomponent,main里面引入变成默认的,然后menu里面index,import也是默认import,module,这样就只需要在view下创建文件和维护modules了

现在不就是这样的么？在 `menu/modules` 下维护导航菜单，在 `views/windows` 下创建窗口页面

**Comment by slowpack** [comment]
好吧,我才发现是打算把页面都当成windows(窗口)来看,这样也行,就是会显得views/windows的东西非常多,我觉得把它当成一个子导航的集合会好一点

**Comment by slowpack** [comment]
> 好吧,我才发现是打算把页面都当成windows(窗口)来看,这样也行,就是会显得views/windows的东西非常多,我觉得把它当成一个子导航的集合会好一点
