### ISSUE TITLE
如何实现方便快速的修改单个窗口的宽度哪？

### ISSUE THREAD

**Issue by TerryXu-98** [hooray/one-step-admin#3]
默认的窗口宽度是800px 假如其中的一个或几个窗口我想设置宽度为1200px其它的窗口还是使用默认的宽度  怎么方便的实现哪？
是直接修改样式  还是通过添加新的配置项哪

**Comment by hooray** [comment]
目前不支持单个窗口设置，可以在这个全局修改窗口的宽度 https://github.com/one-step-admin/basic/blob/main/src/assets/styles/globals.scss#L16-L17
