### ISSUE TITLE
Fantastic-admin的响应式菜单会比one-step-admin的菜单更优

### ISSUE THREAD

**Issue by chaegumi** [hooray/one-step-admin#5]
one-step-admin的响应式在手机中体验感没fantastic-admin好，菜单一直占用了左侧位置，好像不是基础版才那样，专业版一样的问题

**Comment by hooray** [comment]
One-step-admin 不支持移动端，或者说 One-step-admin 本身就是为了更大的屏幕服务的，所以不需要考虑小屏
