### ISSUE TITLE
请问，关于替换ui库功能，是指在没开发业务前替换，还是开发完业务后可以灵活替换？

### ISSUE THREAD

**Issue by HZHWonG** [hooray/one-step-admin#6]
比如：我已经使用Element Plus写了大量业务，然后领导突然说ui不好看，要换成Ant Design Vue。我是按照说明文档那样替换配置文件的ui引用就行了，还是替换完ui库后，要重新用新ui的组件去写业务？谢谢解答！

**Comment by hooray** [comment]
业务开展前可以根据需要替换UI组件库，然后再进行开发。

对于你的场景，如果要替换UI组件库，那业务代码里的UI组件也要进行替换调整

**Comment by HZHWonG** [comment]
> 业务开展前可以根据需要替换UI组件库，然后再进行开发。
> 
> 对于你的场景，如果要替换UI组件库，那业务代码里的UI组件也要进行替换调整

明白了，谢谢大佬解答！
